# Projeto Final — Análise do Mercado de Trabalho em Dados
Autores: João, Roberto e Tereza.

In [33]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sazidthe1/data-science-salaries")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Casa\.cache\kagglehub\datasets\sazidthe1\data-science-salaries\versions\2

In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [35]:
df = pd.read_csv(path + '/data_science_salaries.csv')
df.head()

,job_title,experience_level,employment_type,work_models,work_year,employee_residence,salary,salary_currency,salary_in_usd,company_location,company_size
0,Data Engineer,Mid-level,Full-time,Remote,2024,United States,148100,USD,148100,United States,Medium
1,Data Engineer,Mid-level,Full-time,Remote,2024,United States,98700,USD,98700,United States,Medium
2,Data Scientist,Senior-level,Full-time,Remote,2024,United States,140032,USD,140032,United States,Medium
3,Data Scientist,Senior-level,Full-time,Remote,2024,United States,100022,USD,100022,United States,Medium
4,BI Developer,Mid-level,Full-time,On-site,2024,United States,120000,USD,120000,United States,Medium

In [36]:
def data_science_salaries_csv(caminho):
    return pd.read_csv(caminho)

In [38]:
# ... (mantendo as funções anteriores)

def vagas_por_cargo(df: pd.DataFrame) -> pd.DataFrame:
    """
    Conta quantos registros existem por cargo (proxy de vagas).
    """
    # Ajustando para garantir que as colunas se chamem 'cargo' e 'qtd_vagas'
    return (
        df["cargo"].value_counts()
          .reset_index()
          .rename(columns={"count": "qtd_vagas"})
    )

# Re-definindo as outras funções para garantir integridade se necessário
def carregar_dados_tratados(caminho_csv: str) -> pd.DataFrame:
    df = pd.read_csv(caminho_csv)
    df = df.rename(columns={
        "job_title": "cargo",
        "experience_level": "nivel_experiencia",
        "employment_type": "tipo_contrato",
        "work_models": "modalidade_trabalho",
        "salary_in_usd": "salario_usd",
        "employee_residence": "pais_residencia",
        "company_location": "pais_empresa",
        "company_size": "porte_empresa",
        "work_year": "ano"
    })
    df["salario_usd"] = pd.to_numeric(df["salario_usd"], errors="coerce")
    df["ano"] = pd.to_numeric(df["ano"], errors="coerce")
    df = df.dropna(subset=["salario_usd", "nivel_experiencia", "cargo"])
    return df

def filtrar_por_cargos(df: pd.DataFrame, lista_cargos: list[str]) -> pd.DataFrame:
    return df[df["cargo"].isin(lista_cargos)].copy()

def salario_medio_por_modalidade(df: pd.DataFrame) -> pd.DataFrame:
    return df.groupby("modalidade_trabalho")["salario_usd"].mean().reset_index().sort_values("salario_usd", ascending=False)

## Pergunta 1 – Progressão salarial por nível de experiência

Queremos entender como o salário médio varia entre os níveis de experiência (EN, MI, SE, EX) e se essa progressão é parecida entre os principais cargos de dados (Data Analyst, Data Scientist, Data Engineer).

In [39]:
# As funções já foram definidas na célula anterior, então não é necessário importar de 'sistema'
caminho = "data_science_salaries.csv"
df = carregar_dados_tratados(caminho)

df.head()

,cargo,nivel_experiencia,tipo_contrato,modalidade_trabalho,ano,pais_residencia,salary,salary_currency,salario_usd,pais_empresa,porte_empresa
0,Data Engineer,Mid-level,Full-time,Remote,2024,United States,148100,USD,148100,United States,Medium
1,Data Engineer,Mid-level,Full-time,Remote,2024,United States,98700,USD,98700,United States,Medium
2,Data Scientist,Senior-level,Full-time,Remote,2024,United States,140032,USD,140032,United States,Medium
3,Data Scientist,Senior-level,Full-time,Remote,2024,United States,100022,USD,100022,United States,Medium
4,BI Developer,Mid-level,Full-time,On-site,2024,United States,120000,USD,120000,United States,Medium